[build]
  publish = "."

[[redirects]]
  from = "/fuse-energy-referral-code"
  to = "/fuse-energy-referral-code/"
  status = 301

[[redirects]]
  from = "/how-to-use-fuse-energy-referral-code"
  to = "/how-to-use-fuse-energy-referral-code/"
  status = 301

[[redirects]]
  from = "/fuse-energy-referral-code-faq"
  to = "/fuse-energy-referral-code-faq/"
  status = 301

[[redirects]]
  from = "/energy-referral-codes"
  to = "/energy-referral-codes/"
  status = 301
